---
base_path: '/Users/apasupulate/Documents/Experimentation/music_generation_rnn'
url: 'http://roaringjelly.org/music/RJ_AllSets.abc'
#url: 'https://raw.githubusercontent.com/aamini/introtodeeplearning/master/mitdeeplearning/data/irish.abc'

epochs: 2500
learning_rate: 1e-3
rnn_units: 1024
embeddings_dim: 256
recurrent_activation: 'sigmoid'
recurrent_initializer: 'glorot_uniform'
batch_size: 4
segment_len: 200
